version: "3.7"

services:
  mysql:
    image: mysql:8.0.27
    ports:
      - 4000:4000
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: books

  flask:
    image: esneidergrvc/flask-api:v1
    ports:
      - 3000:3000

  angular:
    image: esneidergrvc/angular-ui:v1
    ports:
      - 4200:4200
