version: "3.7"

services:
  mysql:
    image: mysql:8.0.27
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: books
    ports:
      - 32000:3306

  flask:
    image: api

    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: books

    ports:
      - 5000:5000
    links:
      - mysql
