version: "3.7"

services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: books

  flask:
    image: esneidergrvc/flask-api:v1
    ports:
      - 3000:3000
    depends_on:
      - mysql

  angular:
    image: esneidergrvc/angular-ui:v1
    command: npm install --save-dev package.json
    ports:
      - 4200:4200
