version: "3.7"

services:
  mysql:
    image: mysql:8.0.27
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: books
    ports:
      - 32000:3306

  angular:
    image: ui
    ports:
      - 4200:4200

  flask:
    image: esneidergrvc/flask-api:v2

    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: books

    ports:
      - 5000:5000
    depends_on:
      - mysql
    links:
      - mysql
